// src/components/funding/ProposalGenerator.tsx
"use client";

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Loader2, FileText, Copy, Info } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { FindFundingOutput } from "@/ai/flows/find-funding-opportunities";
import { GenerateFundingProposalOutput } from "@/ai/flows/generate-funding-proposal";

interface ProposalGeneratorProps {
  opportunity: FindFundingOutput['opportunities'][0] | null;
  proposal: GenerateFundingProposalOutput | null;
  isLoading: boolean;
  error: string | null;
}

export default function ProposalGenerator({ opportunity, proposal, isLoading, error }: ProposalGeneratorProps) {
  const { toast } = useToast();

  const handleCopyText = (textToCopy: string, sectionName: string) => {
    navigator.clipboard.writeText(textToCopy);
    toast({ description: `Copied ${sectionName} to clipboard!` });
  };

  if (isLoading) {
    return (
      <Card className="w-full max-w-4xl mx-auto shadow-2xl glassmorphism">
        <CardContent className="py-20 text-center">
          <Loader2 className="h-12 w-12 text-primary mx-auto animate-spin mb-4" />
          <p className="text-lg text-muted-foreground">Generating your proposal for <strong className="text-primary">{opportunity?.title}</strong>...</p>
        </CardContent>
      </Card>
    );
  }

  if (error) {
    return (
      <Alert variant="destructive" className="my-8">
        <AlertTitle>Proposal Generation Error</AlertTitle>
        <AlertDescription>{error}</AlertDescription>
      </Alert>
    );
  }

  if (proposal && opportunity) {
    return (
      <Card className="w-full max-w-4xl mx-auto shadow-2xl glassmorphism">
        <CardHeader className="text-center">
          <CardTitle className="text-3xl text-primary">{proposal.title}</CardTitle>
          <CardDescription>
            This is a draft generated by AI for the <strong className="text-foreground">{opportunity.fundingName}</strong> grant by <strong className="text-foreground">{opportunity.organization}</strong>.
            <br />
            Review, edit, and use this as a foundation for your official application.
          </CardDescription>
        </CardHeader>
        <CardContent className="flex flex-col items-start space-y-6 pt-6 text-black">
          <div className="w-full space-y-6 rounded-lg bg-white p-6 shadow-inner">
            {Object.entries(proposal).map(([key, value]) => {
              if (key === 'title') return null;
              const sectionTitle = key.replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase());
              
              return (
                <div key={key}>
                  <div className="flex justify-between items-center mb-2 border-b pb-2">
                    <h4 className="text-xl font-bold text-gray-800">{sectionTitle}</h4>
                    <Button variant="ghost" size="sm" onClick={() => handleCopyText(value, sectionTitle)}>
                      <Copy className="h-4 w-4 mr-1"/> Copy Section
                    </Button>
                  </div>
                  <p className="text-base text-gray-700 whitespace-pre-wrap leading-relaxed">{value}</p>
                </div>
              );
            })}
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className="w-full max-w-2xl mx-auto shadow-2xl glassmorphism">
      <CardContent className="py-20 text-center">
        <FileText className="h-16 w-16 text-primary/30 mx-auto mb-4" />
        <h3 className="text-2xl font-semibold text-primary mb-2">Ready to Write?</h3>
        <p className="text-muted-foreground">
          First, find a funding opportunity using the "Funding Finder" tab. Then, click "Generate Proposal" on any funding card to have the AI write a first draft for you here.
        </p>
      </CardContent>
    </Card>
  );
}
